application: compute-engine-sandbox
version: 1
runtime: go
api_version: go1

inbound_services:
- warmup
- channel_presence
- mail

handlers:

- url: /.*
  script: _go_app
  secure: always
  login: required
